GTNewHorizons/Railcraft

- src/main/java/mods/railcraft/common/util/crafting/CartFilterRecipe.java
Fixes https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/13.
> Fixed issue by disabling crafting in certain conditions.

- build.gradle
- dependencies.gradle
- src/main/java/mods/railcraft/common/modules/ModuleAdvancedTanks.java
we override these anyway elsewhere
also add NEI to runClient so you can do things
> remove default GTNH tank recipes

- src/main/resources/assets/railcraft/lang/en_US.lang
Addresses GTNewHorizons/GT-New-Horizons-Modpack#9180
> Machine names are visible once more

- src/main/java/mods/railcraft/common/items/ItemPlate.java
- src/main/java/mods/railcraft/common/modules/ModuleFactory.java
- src/main/java/mods/railcraft/common/modules/ModuleSteam.java
- src/main/java/mods/railcraft/common/modules/ModuleTransport.java
- src/main/java/mods/railcraft/common/util/crafting/BlastFurnaceCraftingManager.java
- src/main/resources/assets/railcraft/lang/de_DE.lang
- src/main/resources/assets/railcraft/lang/en_US.lang
fix Advanced Coke Oven Making Coal Coke from Charcoal #9093
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9260
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/834
* https://github.com/GTNewHorizons/bartworks/pull/77
> Bf recipe remove

- build.gradle
- gradle.properties
the iron dupe isn't in this code but might as well submit the build script update
> build script update

- .gitignore
- build.gradle
- src/main/java/mods/railcraft/common/carts/EntityCartTank.java
Fixes GTNewHorizons/GT-New-Horizons-Modpack#7393
> Tank cart fix

- .editorconfig
- .github/scripts/test-no-crash-reports.sh
- .github/scripts/test_no_error_reports
- .github/workflows/build-and-test.yml
- build.gradle
- dependencies.gradle
- src/main/java/mods/railcraft/common/blocks/machine/alpha/TileAnchorWorld.java
Fix logging so
`9 chunks and is ticking at <- 120,58,1,292>` is more clear, will now be:
`9 chunks and is ticking at <x- 120 y58 z1,292>`
update buildscript and supporting deps
> update logging to be more accurate

- src/main/java/mods/railcraft/common/fluids/FluidHelper.java
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10014
> Fix desync on right click with fluid container

- src/main/java/mods/railcraft/common/util/network/PacketCurrentItemNBT.java
> fix packethack with nbt

- src/main/java/mods/railcraft/common/blocks/machine/beta/TileTankIronValve.java
i am curious about why nobody notice that is broken
> Fix external drain from railcraft tank never worked

- src/main/java/mods/railcraft/common/blocks/machine/gamma/TileFluidLoader.java
- src/main/java/mods/railcraft/common/blocks/machine/gamma/TileFluidUnloader.java
- src/main/java/mods/railcraft/common/fluids/FluidHelper.java
- src/main/java/mods/railcraft/common/fluids/FluidItemHelper.java
- src/main/java/mods/railcraft/common/util/inventory/InvTools.java
Also apply gt++ asm patches so that we can remove them from gt++.
> Fix bad fluid container handling, eating IC2 cells and similar

- src/main/resources/assets/railcraft/lang/en_US.lang
> Remove BOM in en_US.lang

- src/main/java/mods/railcraft/common/blocks/aesthetics/slab/BlockRailcraftSlab.java
Slabs don't block light, I want to use them as roof, this fixes that.
> fix slab not blocking light

- build.gradle
- src/main/java/mods/railcraft/common/blocks/aesthetics/brick/EnumBrick.java
- src/main/java/mods/railcraft/common/blocks/aesthetics/stairs/BlockFactoryStairs.java
- src/main/java/mods/railcraft/common/blocks/machine/alpha/TileRockCrusher.java
- src/main/java/mods/railcraft/common/core/Railcraft.java
- src/main/java/mods/railcraft/common/core/RailcraftConfig.java
- src/main/java/mods/railcraft/common/gui/containers/ContainerRockCrusher.java
- src/main/java/mods/railcraft/common/modules/ModuleFactory.java
- src/main/java/mods/railcraft/common/modules/ModuleMagic.java
- src/main/java/mods/railcraft/common/plugins/craftguide/RockCrusherPlugin.java
- src/main/java/mods/railcraft/common/util/misc/Game.java
Reverts & adjusts 6f349d4bb03f96141d581f9a2bf0dcfe71605f93 to keep content when outside of GTNH.
@Dream-Master I suggest we merge this after stable.
> Fix Rock Crusher

- README.md
Clarify where to find the GTNH issue tracker, and that we don't require CLA signatures.
> Clarify things in the README

- src/main/java/mods/railcraft/common/blocks/signals/ItemSignalBlockSurveyor.java
- src/main/java/mods/railcraft/common/blocks/signals/ItemSignalTuner.java
- src/main/java/mods/railcraft/common/items/ItemCrowbar.java
- src/main/java/mods/railcraft/common/items/ItemSteelArmor.java
- src/main/java/mods/railcraft/common/modules/ModuleCore.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/BuildcraftPlugin.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/actions/ActionProvider.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/actions/Actions.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/Trigger.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerAspect.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerEngine.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerHasCart.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerHasWork.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerLowFuel.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerMaintenance.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerProvider.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/TriggerTemp.java
- src/main/java/mods/railcraft/common/plugins/buildcraft/triggers/Triggers.java
- src/main/java/mods/railcraft/common/plugins/ic2/IC2Plugin.java
- src/main/java/mods/railcraft/common/plugins/ic2/TileIC2Delegate.java
- src/main/java/mods/railcraft/common/plugins/ic2/TileIC2EmitterDelegate.java
- src/main/java/mods/railcraft/common/plugins/ic2/TileIC2MultiEmitterDelegate.java
- src/main/java/mods/railcraft/common/plugins/ic2/TileIC2SinkDelegate.java
I think I fixed all of the lacking @Optional things, so this should work now. May require more testing than me successfully launching it thrice under different conditions.
> IC2 and BC are no longer hard dependencies of Railcraft NH

- src/main/java/mods/railcraft/common/blocks/aesthetics/stairs/BlockFactoryStairs.java
we use the one from chisel and they just conflict.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14460
> Disable recipe for packed ice stairs in gtnh

- src/main/java/mods/railcraft/common/blocks/machine/beta/TileTankBase.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14994
> do not add color data when not needed

- src/main/resources/assets/railcraft/lang/cs_CZ.lang
- src/main/resources/assets/railcraft/lang/de_DE.lang
- src/main/resources/assets/railcraft/lang/en_US.lang
- src/main/resources/assets/railcraft/lang/es_AR.lang
- src/main/resources/assets/railcraft/lang/es_ES.lang
- src/main/resources/assets/railcraft/lang/es_MX.lang
- src/main/resources/assets/railcraft/lang/es_UY.lang
- src/main/resources/assets/railcraft/lang/es_VE.lang
- src/main/resources/assets/railcraft/lang/fr_FR.lang
- src/main/resources/assets/railcraft/lang/hr_HR.lang
- src/main/resources/assets/railcraft/lang/hu_HU.lang
- src/main/resources/assets/railcraft/lang/it_IT.lang
- src/main/resources/assets/railcraft/lang/ja_JP.lang
- src/main/resources/assets/railcraft/lang/ko_KR.lang
- src/main/resources/assets/railcraft/lang/nl_NL.lang
- src/main/resources/assets/railcraft/lang/no_NO.lang
- src/main/resources/assets/railcraft/lang/pl_PL.lang
- src/main/resources/assets/railcraft/lang/pt_BR.lang
- src/main/resources/assets/railcraft/lang/pt_PT.lang
- src/main/resources/assets/railcraft/lang/ru_RU.lang
- src/main/resources/assets/railcraft/lang/sr_SP.lang
- src/main/resources/assets/railcraft/lang/zh_CN.lang
- src/main/resources/assets/railcraft/lang/zh_TW.lang
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15991
> Fix lapo loader upgrade name

- dependencies.gradle
- src/main/java/mods/railcraft/common/worldgen/VillagerTradeHandler.java
> Fix Trackman villager trades in NEI

- src/main/java/mods/railcraft/common/worldgen/VillagerTradeHandler.java
fixes https://discord.com/channels/181078474394566657/234936569360809996/1326953488118317249
relevent both for GTNH and non-GTNH.
> Fix a trivial emerald loop

- src/main/java/mods/railcraft/common/blocks/RailcraftBlocks.java
- src/main/java/mods/railcraft/common/blocks/machine/BlockMachine.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18764
Tested in full pack.
Was able to break the blocks with a lower level of tool, but was slower.
> Adjust harvest level for water tank and coke oven brick

- src/main/java/mods/railcraft/common/blocks/RailcraftBlocks.java
- src/main/java/mods/railcraft/common/blocks/machine/BlockMachine.java
Missed the previous pr.
Also allow nothing to drop if the tool is incorrect
> Adjust harvest level for water tank and coke oven brick pt 2

- dependencies.gradle
- src/main/java/mods/railcraft/common/blocks/ore/ItemOre.java
- src/main/java/mods/railcraft/common/items/firestone/FirestoneTickHandler.java
- src/main/java/mods/railcraft/common/items/firestone/IItemFirestoneBurning.java
- src/main/java/mods/railcraft/common/items/firestone/ItemFirestoneCracked.java
- src/main/java/mods/railcraft/common/items/firestone/ItemFirestoneCut.java
- src/main/java/mods/railcraft/common/items/firestone/ItemFirestoneRaw.java
Very sorry I screwed up the other PR, I won't name my PR branches "master" anymore :|
This is just a compatibility layer the Gregtech Items can implement later.
No further changes needed probably (Aged well)
> Firestone burn API

- dependencies.gradle
- src/main/java/mods/railcraft/common/blocks/machine/epsilon/TileElectricFeeder.java
- src/main/java/mods/railcraft/common/blocks/machine/gamma/TileEnergyLoader.java
The title pretty much.
They both take 1 Amp of any voltage. Should definitely be looked at by someone who knows about the GT energy net
> add GregTech energy net compatibility for the Electric Feeder and Energy Loader

- src/main/java/mods/railcraft/common/carts/EntityCartTank.java
Open up modification for inheritance of the tank cart.
I wanna make an iron tank carts mod, and this is the smallest change that allows that
> Tankcart access

- src/main/java/mods/railcraft/common/blocks/machine/BlockMachine.java
Copied break logic from PersonalSpace. Didnt know willHarvest is exactly for this purpose.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19659
> Rework block breaking to fix anchors not storing their time
